project:
  type: website

website:
  title: "Shuaiheng Tao's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: Projects
      - href: Courses.qmd
        text: Courses
  page-footer:
    right: "&copy; 2024, Shuaiheng Tao"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto

